### ISSUE TITLE
Poor visual contrast on dark backgrounds

### ISSUE THREAD

**Issue by MrUltimate** [TheBoredTeam/boring.notch#104]
Hi all,

Just wanted to note that there are instances where it's really hard to see the notch on dark or black backgrounds. Please see screen shot below, as a primarily a dark mode user it, it may help to add a very light stroke around the notch.

<img width="506" alt="image" src="https://github.com/user-attachments/assets/6151740c-f996-4553-bb5f-d5a590d590df">

You'll notice that this is how Apple also deals with the issue to ensure some contrast on dark/black backgrounds:

<img width="456" alt="image" src="https://github.com/user-attachments/assets/882a2556-fd4f-44da-a69e-6831aa6b2c87">

**Comment by iamharshdev** [comment]
Yeah we have fixed the layout. Should be up soon.

**Comment by iamharshdev** [comment]
Do take a look at the second image @richardkunkli

**Comment by MrUltimate** [comment]
Thank you! I'm a product designer so I notice these little details 🙂

**Comment by richardkunkli** [comment]
Hey,
I am totally agree with you. Note that iOS is constantly analyzing the content underneath and using the border when it's needed, but for the same behavior we would have to ask for Screen recording permission and analyze the whole screen. (Users would not grant the permission for that, also the CPU load would be **much higher** because of image processing) I'll take a look at the possibilities and trying to find a different workaround. Also I can see a small backdrop blur on iOS when the notch is open, we could do that, but I believe it's unnecessary because of screen size differences.

**Comment by MrUltimate** [comment]
Thanks for your in-depth response, @richardkunkli 

I think the dynamic color option might be overkill. Personally, I was just looking for a thin white stroke at 8% or 16% opacity. That would be enough to create an "edge" to contrast against the darker background. The most I could think of, it pulling the dominant color from an album artwork like the audio waveform does (perhaps reuse that same logic?)

The blur would be cool as well but wouldn't really work on pure black backgrounds, like I use on an OLED monitor!

**Comment by richardkunkli** [comment]
Of course it's reusable. Everything is componentized. I'll experiment with that a little. The backdrop blur may will be implemented later.

**Comment by richardkunkli** [comment]
Also I suggest you to join us on Discord and try our prerelease. Feedbacks are welcome.

**Comment by MrUltimate** [comment]
Yes, thank you! I'm already in there!
