### ISSUE TITLE
Can't open boringNotch.app, even with right click > open

### ISSUE THREAD

**Issue by BitGrub** [TheBoredTeam/boring.notch#115]
<img width="372" alt="image" src="https://github.com/user-attachments/assets/827fd8a9-93e3-45dd-a482-ba83cfea562f">

**Comment by BitGrub** [comment]
Version [Sleeping Snail 🐌](https://github.com/TheBoredTeam/boring.notch/releases/tag/sleeping-snail)
MacOS 15.0 Sequoia

**Comment by gitultra75848** [comment]
> Version [Sleeping Snail 🐌](https://github.com/TheBoredTeam/boring.notch/releases/tag/sleeping-snail) MacOS 15.0 Sequoia

Try using the Terminal. `sudo open -a /Applications/BoringNotch.app`

**Comment by BitGrub** [comment]
Same pop-up

**Comment by gitultra75848** [comment]
> Same pop-up

`sudo xattr -dr com.apple.quarantine /Applications/BoringNotch.app`
Then try opening it again.

**Comment by BitGrub** [comment]
> `sudo xattr -dr com.apple.quarantine /Applications/BoringNotch.app`
> 
> Then try opening it again.

That's a bit too dodgy for me, tbh

**Comment by gitultra75848** [comment]
> > `sudo xattr -dr com.apple.quarantine /Applications/BoringNotch.app`
> > Then try opening it again.
> 
> That's a bit too dodgy for me, tbh

I get it, here's a breakdown of the command if it makes you feel better.

`sudo` - run command as superuser

`xattr` - display and manipulate attributes

`-dr` - delete the written data from the targetted file and everything in said targetted file

`com.apple.quarantine` - the cause of the error, the app is in quarantine because the creator doesn't have a developer account with apple.

`/Applications/BoringNotch.app` - the target file to remove quarantine from.

**Comment by richardkunkli** [comment]
Hi,
We have a warning under the download button that helps with this problem.

**Comment by richardkunkli** [comment]
> [!warning]
> We don't have Apple Developer account yet. The applications will show a popup on first start. Click Okay, then go to Settings / Privacy & Security and scroll down until you see a button Open anyway. You'll have to do this once.
